CREATE SCHEMA IF NOT EXISTS rainbowl;

CREATE OR REPLACE FUNCTION rainbowl.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS rainbowl.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_customer_id TEXT UNIQUE,
    name TEXT NOT NULL,
    phone_number TEXT,
    location TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rainbowl.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_product_id TEXT UNIQUE,
    name TEXT NOT NULL,
    selling_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    cost_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rainbowl.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number TEXT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL REFERENCES rainbowl.customers(id),
    order_date DATE NOT NULL,
    requested_collection_date DATE,
    fulfilled_at TIMESTAMPTZ,
    payment_status TEXT NOT NULL DEFAULT 'unpaid'
        CHECK (payment_status IN ('unpaid', 'partial', 'paid', 'refunded')),
    fulfillment_status TEXT NOT NULL DEFAULT 'pending'
        CHECK (fulfillment_status IN ('pending', 'processing', 'ready', 'delivered', 'cancelled')),
    amount_paid NUMERIC(12, 2) NOT NULL DEFAULT 0,
    notes TEXT,
    source TEXT NOT NULL DEFAULT 'app',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rainbowl.order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES rainbowl.orders(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES rainbowl.products(id),
    quantity NUMERIC(12, 3) NOT NULL CHECK (quantity > 0),
    unit_cost NUMERIC(12, 2) NOT NULL DEFAULT 0,
    unit_price NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_type TEXT NOT NULL DEFAULT 'amount'
        CHECK (discount_type IN ('none', 'amount', 'percent')),
    discount_value NUMERIC(12, 2) NOT NULL DEFAULT 0,
    discount_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    line_subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    line_total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    line_margin NUMERIC(12, 2) NOT NULL DEFAULT 0,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS rainbowl.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES rainbowl.orders(id) ON DELETE CASCADE,
    payment_date DATE NOT NULL,
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    method TEXT NOT NULL DEFAULT 'cash',
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rainbowl.order_reminder_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES rainbowl.orders(id) ON DELETE CASCADE,
    reminder_date DATE NOT NULL,
    days_before INTEGER NOT NULL CHECK (days_before IN (1, 2)),
    recipient_email TEXT NOT NULL,
    email_subject TEXT,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (order_id, reminder_date, days_before)
);

CREATE TABLE IF NOT EXISTS rainbowl.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_date DATE NOT NULL,
    expense_category TEXT NOT NULL,
    product_id BIGINT REFERENCES rainbowl.products(id),
    description TEXT,
    quantity NUMERIC(12, 3),
    uom TEXT,
    amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS rainbowl.account_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL,
    opening_balance NUMERIC(12, 2) NOT NULL DEFAULT 0,
    money_in NUMERIC(12, 2) NOT NULL DEFAULT 0,
    money_out NUMERIC(12, 2) NOT NULL DEFAULT 0,
    balance_in_bank NUMERIC(12, 2) NOT NULL DEFAULT 0,
    amount_in_account NUMERIC(12, 2) NOT NULL DEFAULT 0,
    difference NUMERIC(12, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO rainbowl.products (legacy_product_id, name, selling_price, cost_price, is_active)
VALUES
    ('RB-01', 'Maxi Fruit Bowl', 3500.00, 3000.00, TRUE),
    ('RB-02', 'Mini Fruit Bowl', 1500.00, 1250.00, TRUE),
    ('RB-03', 'Maxi Bowling Pin', 5000.00, 3800.00, TRUE),
    ('RB-04', 'Mini Bowling Pin', 3000.00, 2100.00, TRUE)
ON CONFLICT (legacy_product_id) DO UPDATE SET
    name = EXCLUDED.name,
    selling_price = EXCLUDED.selling_price,
    cost_price = EXCLUDED.cost_price,
    is_active = EXCLUDED.is_active;

CREATE INDEX IF NOT EXISTS idx_rainbowl_customers_name
    ON rainbowl.customers (LOWER(name));

CREATE INDEX IF NOT EXISTS idx_rainbowl_products_name
    ON rainbowl.products (LOWER(name));

CREATE INDEX IF NOT EXISTS idx_rainbowl_orders_customer_id
    ON rainbowl.orders (customer_id);

CREATE INDEX IF NOT EXISTS idx_rainbowl_orders_order_date
    ON rainbowl.orders (order_date DESC);

CREATE INDEX IF NOT EXISTS idx_rainbowl_orders_statuses
    ON rainbowl.orders (payment_status, fulfillment_status);

CREATE INDEX IF NOT EXISTS idx_rainbowl_order_items_order_id
    ON rainbowl.order_items (order_id);

CREATE INDEX IF NOT EXISTS idx_rainbowl_order_items_product_id
    ON rainbowl.order_items (product_id);

CREATE INDEX IF NOT EXISTS idx_rainbowl_payments_order_id
    ON rainbowl.payments (order_id);

CREATE INDEX IF NOT EXISTS idx_rainbowl_order_reminders_order_id
    ON rainbowl.order_reminder_notifications (order_id);

CREATE INDEX IF NOT EXISTS idx_rainbowl_order_reminders_reminder_date
    ON rainbowl.order_reminder_notifications (reminder_date DESC);

CREATE INDEX IF NOT EXISTS idx_rainbowl_expenses_expense_date
    ON rainbowl.expenses (expense_date DESC);

CREATE INDEX IF NOT EXISTS idx_rainbowl_expenses_product_id
    ON rainbowl.expenses (product_id);

CREATE INDEX IF NOT EXISTS idx_rainbowl_account_snapshots_snapshot_date
    ON rainbowl.account_snapshots (snapshot_date DESC);

DROP TRIGGER IF EXISTS trg_rainbowl_customers_updated_at ON rainbowl.customers;
CREATE TRIGGER trg_rainbowl_customers_updated_at
BEFORE UPDATE ON rainbowl.customers
FOR EACH ROW
EXECUTE FUNCTION rainbowl.set_updated_at();

DROP TRIGGER IF EXISTS trg_rainbowl_products_updated_at ON rainbowl.products;
CREATE TRIGGER trg_rainbowl_products_updated_at
BEFORE UPDATE ON rainbowl.products
FOR EACH ROW
EXECUTE FUNCTION rainbowl.set_updated_at();

DROP TRIGGER IF EXISTS trg_rainbowl_orders_updated_at ON rainbowl.orders;
CREATE TRIGGER trg_rainbowl_orders_updated_at
BEFORE UPDATE ON rainbowl.orders
FOR EACH ROW
EXECUTE FUNCTION rainbowl.set_updated_at();

CREATE OR REPLACE VIEW rainbowl.sales_lines AS
SELECT
    orders.order_date AS date,
    COALESCE(products.legacy_product_id, products.id::TEXT) AS product_id,
    products.name AS product_name,
    COALESCE(customers.legacy_customer_id, customers.id::TEXT) AS customer_id,
    customers.name AS customer_name,
    order_items.quantity AS quantity,
    order_items.unit_cost AS cost_price,
    order_items.unit_price AS selling_price,
    order_items.discount_amount AS discount,
    order_items.line_margin AS margin,
    orders.payment_status AS payment_status,
    orders.fulfillment_status AS fulfillment_status
FROM rainbowl.order_items AS order_items
JOIN rainbowl.orders AS orders ON orders.id = order_items.order_id
JOIN rainbowl.customers AS customers ON customers.id = orders.customer_id
JOIN rainbowl.products AS products ON products.id = order_items.product_id;
